#!/bin/bash

curl https://www.mnot.net/cache_docs/#PROXY
curl http://www.httpvshttps.com/
curl http://www.example.com/ 
curl http://in.yahoo.com/
curl http://www.baidu.com/
curl http://www.bing.com/?FORM=Z9FD1&mkt=zh-CN
curl https://www.mnot.net/cache_docs/#PROXY
curl http://www.httpvshttps.com/
curl http://www.example.com/ 
curl http://in.yahoo.com/
curl http://www.baidu.com/
curl http://www.bing.com/?FORM=Z9FD1&mkt=zh-CN
curl http://www.tutorialspoint.com/http/http_requests.htm
curl http://www.columbia.edu/~fdc/sample.html#basics
curl http://www.yandex.com/
curl http://www.quora.com/
curl http://www.google.com
curl https://www.mnot.net/cache_docs/#PROXY
curl http://www.httpvshttps.com/
curl https://www.example.com/ 
curl http://in.yahoo.com/
curl https://www.baidu.com/
curl http://www.bing.com/?FORM=Z9FD1&mkt=zh-CN
curl https://www.mnot.net/cache_docs/#PROXY
curl http://www.example.com/ 
curl http://in.yahoo.com/
curl http://www.baidu.com/
curl http://www.bing.com/?FORM=Z9FD1&mkt=zh-CN
curl http://www.mnot.net/cache_docs/#PROXY
curl http://www.httpvshttps.com/
curl http://www.example.com/ 
curl http://in.yahoo.com/
curl http://www.baidu.com/
curl http://www.bing.com/?FORM=Z9FD1&mkt=zh-CN
curl http://www.tutorialspoint.com/http/http_requests.htm
curl http://www.columbia.edu/~fdc/sample.html#basics
curl http://www.yandex.com/
curl http://www.quora.com/
curl http://www.google.com
